import nbformat as nbf
from nbclient import NotebookClient
nb = nbf.v4.new_notebook()
C = []

def md(s):
    C.append(nbf.v4.new_markdown_cell(s))

def code(s):
    C.append(nbf.v4.new_code_cell(s))
md('# GuidelineForge — Inter-Annotator Agreement & QA Analysis\n**Support-ticket intent + sentiment annotation program, 600 tickets · 3 annotators · 2 rounds**\n\nThis notebook recomputes every statistic in the project from the raw label\nfiles. Metrics are implemented from scratch in `src/agreement.py` and\ncross-validated against scikit-learn / NLTK / the canonical Fleiss (1971)\nworked example — because in a quality-engineering discipline, *the measuring\ninstruments get calibrated first*.\n\n| | |\n|---|---|\n| Corpus | 600 support tickets (520 real Bitext rows + 80 documented ambiguity injections) |\n| Tasks | intent (8 classes) + sentiment (ordinal: negative < neutral < positive) |\n| Design | 180-ticket blind triple-overlap for IAA · 72-item gold set · 48-item calibration set |\n| Rounds | R1 under guidelines v1.0 → disagreement analysis → v2.0 → R2 → tiered QA |')
code('# locate the repo root no matter where Jupyter was launched from\nimport os, pathlib, sys, json\n_cands = [pathlib.Path.cwd(), pathlib.Path.cwd().parent,\n          pathlib.Path.cwd().parent.parent]\nROOT = next(p for p in _cands\n            if (p / "guidelines").exists() and (p / "src").exists())\nos.chdir(ROOT / "notebooks")          # notebook paths are relative to here\nsys.path.insert(0, str(ROOT / "src"))\n\nimport numpy as np\nimport pandas as pd\nfrom agreement import (cohen_kappa, fleiss_kappa, krippendorff_alpha,\n                        bootstrap_ci, per_class_kappa, confusion_pairs,\n                        observed_agreement, run_self_tests)\n\ncorpus = pd.read_csv("../data/raw/support_tickets.csv")\ngold   = pd.read_csv("../data/gold_set.csv")\nr1     = pd.read_csv("../data/annotations/annotations_round1.csv")\nr2     = pd.read_csv("../data/annotations/annotations_round2.csv")\nM      = json.load(open("../results/metrics.json"))\nprint(f"corpus={len(corpus)}  overlap={corpus.in_overlap.sum()}  "\n      f"gold={corpus.is_gold.sum()}  calibration={corpus.is_calibration.sum()}")\nprint(f"R1 labels={len(r1)} (540 overlap + 420 production)  R2 labels={len(r2)}")')
md("## 0 · Instrument calibration — the metrics correct *before* they're trusted\nSelf-tests: perfect-agreement sanity, Cohen vs scikit-learn (bit-exact),\nFleiss vs NLTK **and** the published 0.210 reference value, Krippendorff α\nvs NLTK (16 digits).")
code('run_self_tests()')
md('## 1 · Corpus composition & the taxonomy\nThe corpus mixes organic tickets with five *planted* ambiguity families —\nthe patterns that break real annotation programs. Ambiguity is deliberate:\nagreement statistics are meaningless on trivially easy data.')
code('summ = (corpus.groupby("ambiguity_type")\n        .agg(n=("ticket_id", "count"),\n             in_overlap=("in_overlap", "sum"),\n             gold=("is_gold", "sum")))\nprint(summ.to_string())\nprint("\\nIntent classes:", sorted(corpus.design_intent.unique()))')
md("## 2 · Round 1 — how much did the annotators disagree?\nBackoff ladder: raw unanimity → pairwise Cohen's κ → multi-rater Fleiss' κ →\nKrippendorff's α (ordinal for sentiment, since 'negative-vs-positive' is a\n*larger* error than 'negative-vs-neutral' and α's distance metric prices\nthat in).")
code('ov_ids = corpus[corpus.in_overlap].ticket_id.tolist()\ndef seq(ann, task):\n    piv = ann[ann.ticket_id.isin(ov_ids)].pivot(index="ticket_id",\n                                                columns="annotator",\n                                                values=task)\n    return [piv[a].tolist() for a in ["A1", "A2", "A3"]]\n\ni1, s1 = seq(r1, "intent"), seq(r1, "sentiment")\ni2, s2 = seq(r2, "intent"), seq(r2, "sentiment")\n\nrows = []\nfor name, lab1, lab2 in [("intent", i1, i2), ("sentiment", s1, s2)]:\n    for round_, lab in [("R1", lab1), ("R2", lab2)]:\n        pairs = [cohen_kappa(lab[a], lab[b])\n                 for a, b in [(0, 1), (0, 2), (1, 2)]]\n        rows.append({\n            "task": name, "round": round_,\n            "unanimous": np.mean([len({l[k] for l in lab}) == 1\n                                  for k in range(180)]).round(3),\n            "cohen_mean": np.mean(pairs).round(4),\n            "fleiss": round(fleiss_kappa(lab), 4),\n            "alpha": round(krippendorff_alpha(\n                lab, level="ordinal" if name == "sentiment" else "nominal"), 4),\n        })\nsummary = pd.DataFrame(rows).set_index(["task", "round"])\nsummary')
md('**Reading:** Round-1 intent sits at κ ≈ 0.83 — deceptively "acceptable" —\nwhile sentiment is at 0.67 and **ordinal α drops to 0.61**: partial-credit\non near-misses exposes that the disagreements are *severe* (literal\npositive-vs-correct negative on sarcasm), not borderline. The 95% bootstrap\nCI for Round-1 Fleiss\' κ (intent) is [0.783, 0.880]; Round 2 [0.928, 0.980]\n— the intervals don\'t overlap, so the improvement is not sampling noise.')
code('lo1, hi1 = M["R1"]["fleiss_intent_ci95"]\nlo2, hi2 = M["R2"]["fleiss_intent_ci95"]\nprint(f"Fleiss κ intent 95% CI (bootstrap n=500):  R1 [{lo1}, {hi1}]   R2 [{lo2}, {hi2}]")\n\n# stronger than comparing two CIs: a PAIRED bootstrap over the same items,\n# measuring Δκ directly (items are linked — same tickets, both rounds)\nrng = np.random.default_rng(7)\nN = len(ov_ids)\ndiffs = np.array([fleiss_kappa([[l[k] for k in cols] for l in i2])\n                  - fleiss_kappa([[l[k] for k in cols] for l in i1])\n                  for cols in (rng.integers(0, N, N) for _ in range(500))])\nlo, hi = np.percentile(diffs, [2.5, 97.5])\nprint(f"Δκ intent (paired bootstrap over identical items): "\n      f"+{diffs.mean():.3f}  95% CI [{lo:.3f}, {hi:.3f}]")\nassert hi1 < lo2 and lo > 0\nprint("→ separate CIs disjoint AND paired Δκ CI excludes 0: "\n      "the improvement is statistically real, not sampling noise.")')
md('## 3 · Where does it hurt? — per-class and slice analysis\n**This is the "so what":** an overall κ hides exactly the information a\nQA lead needs. Per-class κ localizes the problem to `cancellation` (0.58)\nand `refund_request` (0.79); the slice map localizes it to three *families*\nof language.')
code('pc = pd.DataFrame({"R1": M["R1"]["per_class_intent_kappa"],\n                   "R2": M["R2"]["per_class_intent_kappa"]}).sort_values("R1")\npc.style.format("{:.3f}").background_gradient(cmap="RdYlGn", axis=None)')
code('from IPython.display import Image, display\ndisplay(Image("../results/figures/fig_slices.png"))\ndisplay(Image("../results/figures/fig_confusion.png"))')
md('The confusion matrix names the mechanism: the off-diagonal mass sits on\n`cancellation ⇄ refund ⇄ billing` (mixed intents) — a **tie-breaking rule**\nproblem, not a taxonomy problem. Deleting `order_changes` or merging classes\nwould address nothing; a precedence hierarchy addresses everything. That\nreasoning — slice → mechanism → targeted rule — is the core QA skill.\n\n## 4 · Agreement is not correctness — the gold-set finding\nThe 16 anger-framed action requests were **75% unanimous** in Round 1 while\nonly **25% matched design intent** — all three annotators faithfully applied\nv1\'s flawed tone-first rule (R4). The gold set is what separates "we agree"\nfrom "we\'re right".')
code('trap = M["R1"]["tone_trap_slice"]\nprint(f"anger-framed action requests (n={trap[\'n\']}):")\nprint(f"  unanimous agreement among annotators: {trap[\'unanimous_agreement\']:.0%}")\nprint(f"  accuracy vs design intent by annotator: {trap[\'accuracy_vs_design\']}")\nprint("\\n  example: \'This is ridiculous. Refund my card for order #3045073 NOW.\'")\nprint("  v1 R4 → feedback_complaints (unanimous, wrong)  |  gold intent: refund_request")\n\nga = pd.DataFrame(M["R1"]["gold_accuracy"])\nga.columns = ["A1 (careful)", "A2 (empathetic)", "A3 (fast)"]\nprint("\\nRound-1 gold accuracy by annotator:")\nga')
md('**Counter-intuitive and important:** the *careful literalist* (A1) scored\n**worse** on gold intent than the *empathetic skimmer* (A2) in Round 1 —\nbecause A1 applied the flawed rule most faithfully. Diligence amplifies\nguideline bugs; it cannot compensate for them. That is precisely why\nguideline revision, not annotator retraining, was the correct intervention.\n\n## 5 · Round 2 — did the revision work?')
code('display(Image("../results/figures/fig_headline.png"))\ndisplay(Image("../results/figures/fig_perclass.png"))\ndisplay(Image("../results/figures/fig_gold.png"))\ndisplay(Image("../results/figures/fig_trend.png"))')
md('## 6 · Tiered QA — rework and audit')
code('qa = M["qa"]\nprint(f"Tier-2 review volume: {qa[\'tier2_review_volume\']}")\nprint(f"rework rate: intent {qa[\'rework_rate_intent\']:.1%} | "\n      f"sentiment {qa[\'rework_rate_sentiment\']:.1%} | either {qa[\'rework_rate_either\']:.1%}")\nprint(f"tier-3 audit: n={qa[\'tier3_audit\'][\'n\']}  pass {qa[\'tier3_audit\'][\'pass_rate_overall\']:.0%}")\nprint(f"final labels vs gold: intent {qa[\'final_gold_intent_acc\']:.3f}  "\n      f"sentiment {qa[\'final_gold_sentiment_acc\']:.3f}")\ncf = M["counterfactual_v1_cost"]\nprint(f"\\ncounterfactual cost of v1.0 (share of R1 production labels the v2 "\n      f"rules would have corrected):\\n  intents {cf[\'r1_production_intents_misrouted_under_v2\']:.1%}, "\n      f"sentiments {cf[\'r1_production_sentiments_corrected_under_v2\']:.1%}")\ndisplay(Image("../results/figures/fig_qa.png"))')
md('## 7 · Conclusions\n\n1. **Overall agreement conceals; slices reveal.** Round-1 intent κ = 0.83\n   looked shippable while mixed intents ran at chance level (κ = 0.03).\n2. **Agreement ≠ correctness.** The anger-framed family agreed-and-wrong at\n   75% unanimity; only the gold set caught it.\n3. **Guidelines, not annotators, were the defect** — and the cheap fix was\n   a rule change (precedence hierarchy, sarcasm rule, politeness rule).\n   Intent κ 0.83 → **0.96**, ordinal α (sentiment) 0.61 → **0.89**.\n4. **QA economics:** steady-state rework ~2–5% (< 15–20% ceiling), audit\n   pass 100%, final gold accuracy 1.00 intent / 0.96 sentiment.\n5. **Known gap (v2.1 backlog):** statement-form policy questions\n   ("i cannot check ur money back guarantee" — no `?`, policy gate misses)\n   and keyword-invisible typos ("acvount") — logged with examples in the\n   QA writeup.')
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
nb_dir = ROOT / 'notebooks'
nb_dir.mkdir(parents=True, exist_ok=True)
path = str(nb_dir / 'agreement_analysis.ipynb')

nb.cells = C
nb.metadata = {'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'}, 'language_info': {'name': 'python', 'version': '3.13'}}
nbf.write(nb, path)
client = NotebookClient(nb, timeout=300, kernel_name='python3', resources={'metadata': {'path': str(nb_dir)}})
client.execute()
nbf.write(nb, path)
print('notebooks/agreement_analysis.ipynb built and executed')

